name: inmateschedular_pro
description: "An innovative solution designed to streamline and optimize scheduling processes in correctional facilities. This application is built to address the inefficiencies and challenges associated with traditional manual scheduling methods, providing a modern, automated approach to inmate and staff management."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  universal_io: ^2.2.2
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  csc_picker: ^0.2.7
  printing: ^5.13.1
  syncfusion_flutter_pdf: ^26.2.8
  dynamic_height_grid_view: ^0.0.4

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/svg/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
  