// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI1HOY1FZ0DMcI3rc5vAfZ-UNNPPXwBuo',
    appId: '1:931168504257:web:436fe131c4a639fb3e8740',
    messagingSenderId: '931168504257',
    projectId: 'inmate-schedular',
    authDomain: 'inmate-schedular.firebaseapp.com',
    storageBucket: 'inmate-schedular.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfNbGrhaJd_0v1EyTb0H5pWRVqfH-kEg',
    appId: '1:931168504257:android:738675cc6066d8fd3e8740',
    messagingSenderId: '931168504257',
    projectId: 'inmate-schedular',
    storageBucket: 'inmate-schedular.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVM4YZosijHtuIxIGxJWN_tN7a0bW5ftI',
    appId: '1:931168504257:ios:3ae07627fd6883683e8740',
    messagingSenderId: '931168504257',
    projectId: 'inmate-schedular',
    storageBucket: 'inmate-schedular.appspot.com',
    iosBundleId: 'com.example.inmateschedularPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI1HOY1FZ0DMcI3rc5vAfZ-UNNPPXwBuo',
    appId: '1:931168504257:web:f456a9347475cc783e8740',
    messagingSenderId: '931168504257',
    projectId: 'inmate-schedular',
    authDomain: 'inmate-schedular.firebaseapp.com',
    storageBucket: 'inmate-schedular.appspot.com',
  );

}